# NumPy vs Lists

In [2]:
heights = [74, 75, 72, 72, 71]
heights_list = [ ele*2.54 for ele in heights ]
heights_list

[187.96, 190.5, 182.88, 182.88, 180.34]

In [4]:
import numpy as np
np_heights = np.array(heights)
np_heights

array([74, 75, 72, 72, 71])

In [6]:
np_heights*2.54

array([187.96, 190.5 , 182.88, 182.88, 180.34])

In [8]:
np_heights**2.54

array([55956.24565534, 57896.93976602, 52194.47588437, 52194.47588437,
       50372.81318993])

#### Numpy comes with its own set of methods and operations

In [13]:
list_1  = [1,2,3]
list_2 = [4,5,6]
list_1 + list_2

[1, 2, 3, 4, 5, 6]

In [15]:
np.array(list_1) + np.array(list_2)

array([5, 7, 9])

In [17]:
np.array(list_1) * np.array(list_2)

array([ 4, 10, 18])

#### Working with N-D arrays

In [20]:
type(np_heights)

numpy.ndarray